FROM tiagopeixoto/graph-tool

RUN pacman -S --noconfirm jupyter-notebook
RUN pacman -S --noconfirm python-matplotlib
RUN pacman -S --noconfirm python-numpy
RUN pacman -S --noconfirm python-pandas
RUN pacman -S --noconfirm python-seaborn
RUN pacman -S --noconfirm python-scikit-learn
# RUN pip install --upgrade pip && pip install -r /requirements.txt